# Generated by Django 4.2.5 on 2023-09-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_currency_code_alter_currency_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currency",
            name="country",
            field=models.CharField(
                blank=True, max_length=60, null=True, verbose_name="Страна валюты"
            ),
        ),
    ]
