# Generated by Django 4.2.5 on 2023-09-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_currency_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currency",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="currency_images/",
                verbose_name="Изображение купюры",
            ),
        ),
    ]
