# Generated by Django 4.2.5 on 2023-09-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_currency_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currency",
            name="country",
            field=models.CharField(
                blank=True,
                help_text="Будет подобрана автоматически",
                max_length=60,
                null=True,
                verbose_name="Страна валюты",
            ),
        ),
    ]
