"""
Страничка с константами для работы проекта.
"""

IMAGE_SIZE = (500, 500)

CURRENCY_CODES = (
    ("AED", "AED"),
    ("ARS", "ARS"),
    ("AUD", "AUD"),
    ("BGN", "BGN"),
    ("BHD", "BHD"),
    ("BND", "BND"),
    ("BRL", "BRL"),
    ("BWP", "BWP"),
    ("CAD", "CAD"),
    ("CHF", "CHF"),
    ("CLP", "CLP"),
    ("CNY", "CNY"),
    ("COP", "COP"),
    ("CZK", "CZK"),
    ("DKK", "DKK"),
    ("EUR", "EUR"),
    ("GBP", "GBP"),
    ("HKD", "HKD"),
    ("HRK", "HRK"),
    ("HUF", "HUF"),
    ("IDR", "IDR"),
    ("ILS", "ILS"),
    ("INR", "INR"),
    ("IRR", "IRR"),
    ("ISK", "ISK"),
    ("JPY", "JPY"),
    ("KWD", "KWD"),
    ("KRW", "KRW"),
    ("KZT", "KZT"),
    ("LKR", "LKR"),
    ("KYD", "KYD"),
    ("MUR", "MUR"),
    ("MXN", "MXN"),
    ("MYR", "MYR"),
    ("NOK", "NOK"),
    ("NPR", "NPR"),
    ("NZD", "NZD"),
    ("OMR", "OMR"),
    ("PHP", "PHP"),
    ("PKR", "PKR"),
    ("PLN", "PLN"),
    ("QAR", "QAR"),
    ("RON", "RON"),
    ("RUB", "RUB"),
    ("SAR", "SAR"),
    ("SEK", "SEK"),
    ("SGD", "SGD"),
    ("THB", "THB"),
    ("TRY", "TRY"),
    ("TTD", "TTD"),
    ("TWD", "TWD"),
    ("USD", "USD"),
    ("VEF", "VEF"),
    ("ZAR", "ZAR"),
)

CURRENCY_COUNTRIES = (
    ("AED", "EmiratiDirham"),
    ("ARS", "Argentine Peso"),
    ("AUD", "Australian Dollar"),
    ("BGN", "Bulgarian Lev"),
    ("BHD", "Bahraini Dinar"),
    ("BND", "Bruneian Dollar"),
    ("BRL", "Brazilian Real"),
    ("BWP", "Botswana Pula"),
    ("CAD", "Canadian Dollar"),
    ("CHF", "Swiss Franc"),
    ("CLP", "Chilean Peso"),
    ("CNY", "Chinese Yuan Renminbi"),
    ("COP", "Colombian Peso"),
    ("CZK", "Czech Koruna"),
    ("DKK", "Danish Krone"),
    ("EUR", "Euro"),
    ("GBP", "British Pound"),
    ("HKD", "Hong Kong Dollar"),
    ("HRK", "Croatian Kuna"),
    ("HUF", "Hungraian Forint"),
    ("IDR", "Indonesian Rupiah"),
    ("ILS", "Israeli Shekel"),
    ("INR", "Indian Rupee"),
    ("IRR", "Iranian rial"),
    ("ISK", "Icelandic Krona"),
    ("JPY", "Japanese Yen"),
    ("KWD", "South Korean Won"),
    ("KRW", "Kuwaiti Dinar"),
    ("KZT", "Kazakhstani Tenge"),
    ("LKR", "Sri Lankan Rupee"),
    ("KYD", "Libyan Dinar"),
    ("MUR", "Mauritian Rupee"),
    ("MXN", "Mexican Peso"),
    ("MYR", "Malaysian Ringgit"),
    ("NOK", "Norwegian Krone"),
    ("NPR", "Nepalese Rupee"),
    ("NZD", "New Zealand Dollar"),
    ("OMR", "Omani Rial"),
    ("PHP", "Philippine Peso"),
    ("PKR", "Pakistani Rupee"),
    ("PLN", "Polish Zloty"),
    ("QAR", "Qatari Riyal"),
    ("RON", "Romanian New Leu"),
    ("RUB", "Russian Ruble"),
    ("SAR", "Saudi Arabian Riyal"),
    ("SEK", "Swedish Krona"),
    ("SGD", "Singapore Dollar"),
    ("THB", "Thai Baht"),
    ("TRY", "Turkish Lira"),
    ("TTD", "Trinidadian Dollar"),
    ("TWD", "Taiwan New Dollar"),
    ("USD", "US Dollar"),
    ("VEF", "Venezuelan Bolivar"),
    ("ZAR", "South African Rand"),
)
CURRENCY_DICT = dict(CURRENCY_COUNTRIES)
